version: "3.9"

services:
  app:
    build: .
    container_name: t3node-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules  # pour éviter les conflits node_modules local

  mongo:
    image: mongo:5
    container_name: t3node-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
