version: "3.9"

services:
  app:
    build: .
    container_name: t3node-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: sh -c "npm run build && npm run seed && node dist/main.js"


  mongo:
    image: mongo:5
    container_name: t3node-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]


volumes:
  mongo-data:
